import { RuntimeContext } from "@mastra/core/runtime-context";
import { typescriptToZodTool } from "./typescript-to-zod";

/**
 * Test the TypeScript to Zod schema generator tool
 */
async function testTypescriptToZod() {
	console.log("Testing TypeScript to Zod tool...\n");

	// Example TypeScript interface (like those generated by quicktype)
	const interfaceString = `
interface RedditPost {
  id: string;
  title: string;
  author: string;
  url: string;
  score: number;
  num_comments: number;
  created_utc: number;
  permalink: string;
  is_video: boolean;
  thumbnail?: string;
}
  `.trim();

	// Sample data for inference
	const sampleData = {
		id: "abc123",
		title: "An interesting post",
		author: "reddit_user",
		url: "https://reddit.com/r/programming/comments/abc123",
		score: 42,
		num_comments: 15,
		created_utc: 1699564800,
		permalink: "/r/programming/comments/abc123/an_interesting_post",
		is_video: false,
		thumbnail: "https://i.redd.it/thumbnail.jpg",
	};

	try {
		const result = await typescriptToZodTool.execute({
			context: {
				interfaceString,
				sampleData,
			},
			runtimeContext: new RuntimeContext(),
		});

		console.log("✅ Success!");
		console.log("\nInterface Name:", result.interfaceName);
		console.log("\nGenerated Zod Schema:");
		console.log("─".repeat(80));
		console.log(result.zodSchema);
		console.log("─".repeat(80));
	} catch (error) {
		console.error("❌ Error:", error);
		throw error;
	}
}

// Run the test
testTypescriptToZod();
